version: '3.8'

services:
  web:
    build: .
    ports:
      - "8080:80"
    depends_on:
      - db
    environment:
      MYSQL_HOST: db
      MYSQL_USER: root
      MYSQL_PASSWORD: testdb
      MYSQL_DATABASE: dockerBD
    volumes:
      - /mnt/c/Users/thabi/Documents/Projects/dockerPhp:/var/www/html  # Syncs your local PHP files with the container

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: testdb
      MYSQL_DATABASE: dockerBD
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
